name: Silpion Craft-Night timely example
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run js test
        env:
          super_secret: ${{secrets.test}}
        run: npx jest
      - name: run python test
        env:
          SECRET: ${{secrets.test}}
        run: python3 test.py
